language: go

dist: xenial
services:
  - docker

go:
- 1.12

go_import_path: go.coder.com/sail

install: true
env:
  - GO111MODULE=on
script:
  - env
  - ci/build.sh
  # Pre-download the code-server binary so we don't hit github rate limits.
  - mkdir -p /tmp/sail-code-server-cache
  - curl -o /tmp/sail/code-server-cache/code-server https://codesrv-ci.cdr.sh/latest-linux
  - chmod +x /tmp/sail/code-server-cache/code-server
  - go test -v ./...

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "bin/sail-linux-amd64"
  skip_cleanup: true
  draft: true
